# -*- coding: utf-8 -*-
"""factorial

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AIT2SOvbZ-pbAmMauCe3KUwMZn8HRgAI
"""

num = int(input("Enter a number: "))

factorial = 1

for i in range(1, num + 1):
    factorial = factorial * i

print("Factorial of", num, "is", factorial)

